x = input('Digite qualquer coisa: ')
print('Abaixo temos uma lista com informações sobre o que você digitou:')
print('Tipo da variavel: ', type(x))
print('Digitou somente letras? ', x.isalpha())
print('Digitou somente números? ', x.isnumeric())
print('Digitou algo alfanumérico? ', x.isalnum())
print('Digitou somente letras maiusculas? ', x.isupper())
print('Digitou somente letras minúsculas? ', x.islower())